=== JiZPaper/VNDB-Description-Translations/description.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/JiZPaper/PaperVN/blob/main/VNDBDescriptions/description.schema.json",
  "title": "PaperVN VNDB description translation",
  "type": "object",
  "required": [
    "schema_version",
    "id",
    "type",
    "name",
    "original_name",
    "language",
    "source_language",
    "source",
    "source_sha256",
    "translation",
    "vndb_url"
  ],
  "properties": {
    "schema_version": {
      "const": 1
    },
    "id": {
      "type": "string",
      "pattern": "^[vc][0-9]+$"
    },
    "type": {
      "enum": [
        "visual_novel",
        "character"
      ]
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "original_name": {
      "type": [
        "string",
        "null"
      ]
    },
    "language": {
      "type": "string",
      "pattern": "^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$"
    },
    "source_language": {
      "const": "en"
    },
    "source": {
      "type": "string",
      "minLength": 1
    },
    "source_sha256": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "translation": {
      "type": "string",
      "minLength": 1
    },
    "vndb_url": {
      "type": "string",
      "pattern": "^https://vndb\\.org/[vc][0-9]+$"
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "type": {
            "const": "visual_novel"
          }
        },
        "required": [
          "type"
        ]
      },
      "then": {
        "properties": {
          "id": {
            "pattern": "^v[0-9]+$"
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "type": {
            "const": "character"
          }
        },
        "required": [
          "type"
        ]
      },
      "then": {
        "properties": {
          "id": {
            "pattern": "^c[0-9]+$"
          }
        }
      }
    }
  ],
  "additionalProperties": false
}

=== JiZPaper/VNDB-Description-Translations/en/visual-novels/004/v4626.json
{
  "schema_version": 1,
  "id": "v4626",
  "type": "visual_novel",
  "name": "Ano Ko no Shojo wa Ore no Mono -Renkinjutsu de Ano Ko no Shikyuu ni Seieki Chuunyuu♪-",
  "original_name": "あの娘の処女は俺のもの ―錬金術であの娘の子宮に精液注入♪―",
  "language": "en",
  "source_language": "en",
  "source": "Make use of the alchemy and science power, gain that pretty girl's virginity!\n\nCollect materials in the forest around the magical school.\nMake items from that materials with alchemy.\nBecome strong enough to attack 6 girls including a beast girl and an elf!\n\n[From [url=http://eng.dlsite.com/work/=/product_id/RE064484.html]DLsite English[/url]]",
  "source_sha256": "bbfeb44acfaa86011109b083881e54d0906a9289dd4e88a8982b31a472aff1b4",
  "translation": "Make use of the alchemy and science power, gain that pretty girl's virginity!\n\nCollect materials in the forest around the magical school.\nMake items from that materials with alchemy.\nBecome strong enough to attack 6 girls including a beast girl and an elf!\n\n[From [url=http://eng.dlsite.com/work/=/product_id/RE064484.html]DLsite English[/url]]",
  "vndb_url": "https://vndb.org/v4626"
}

=== JiZPaper/VNDB-Description-Translations/zh-Hans/visual-novels/031/v31852.json
{
  "schema_version": 1,
  "id": "v31852",
  "type": "visual_novel",
  "name": "Sugar Daddies",
  "original_name": null,
  "language": "zh-Hans",
  "source_language": "en",
  "source": "It is the story of a group of young girls who are supported by sugar daddies. The story takes place on \"Auro Digger Island.\" \"Auro\" is the Samoan word for gold. You will play as the third party Master of Ceremonies, and make decisions for most of the characters in the game.\n\nThe central character is a girl named, \"Dawn.\" The player can edit this name to suit their own tastes. \"Dawn\"  has been lied to, and betrayed by everybody close to her. The player's decisions will directly influence the actions of the various potential Sugar Daddies, and how \"Dawn\" evolves.\n\n[From Patreon]",
  "source_sha256": "45ed109e9bf33a4cf3b4442e04b67b4a5db209ac808aafca774578071fba6e21",
  "translation": "这是关于一群年轻女孩在糖爹的支持下的故事。故事发生在“奥罗迪格岛”。“Auro”是萨摩亚语中黄金的意思。你将扮演第三方司仪，并为游戏中的大多数角色做出决定。\n\n主角是一位名叫“黎明”的女孩。玩家可以根据自己的喜好编辑此名称。“黎明”被所有与她亲近的人欺骗和背叛。玩家的决定将直接影响各种潜在糖爹的行动，以及“黎明”的演变。\n\n[来自帕特伦]",
  "vndb_url": "https://vndb.org/v31852"
}

=== JiZPaper/VNDB-Description-Translations/en/visual-novels/044/v44708.json
{
  "schema_version": 1,
  "id": "v44708",
  "type": "visual_novel",
  "name": "A Hint of Purple",
  "original_name": null,
  "language": "en",
  "source_language": "en",
  "source": "Argue with your Prefrontal Cortex, insult an art critic, befriend the elderly.\n\nA Hint of Purple is a short visual novel about queer love and art. Follow Maya, a once-celebrated painter now paralyzed, as she struggles to accept her new reality and its effects on her relationship.\n\n[From [url=https://dormin42.itch.io/a-hint-of-purple]Itch.io[/url]]",
  "source_sha256": "8107721db4be49cf4e53176b52d1b3ef2d0b9cff3a21aa7dbee06fcdff08d0ac",
  "translation": "Argue with your Prefrontal Cortex, insult an art critic, befriend the elderly.\n\nA Hint of Purple is a short visual novel about queer love and art. Follow Maya, a once-celebrated painter now paralyzed, as she struggles to accept her new reality and its effects on her relationship.\n\n[From [url=https://dormin42.itch.io/a-hint-of-purple]Itch.io[/url]]",
  "vndb_url": "https://vndb.org/v44708"
}

=== JiZPaper/VNDB-Description-Translations/zh-Hans/visual-novels/004/v4081.json
{
  "schema_version": 1,
  "id": "v4081",
  "type": "visual_novel",
  "name": "DT Lords of Genomes",
  "original_name": "DTローズ・オブ・ゲノム",
  "language": "zh-Hans",
  "source_language": "en",
  "source": "You are a DT master. \nYou can change the substance with the collected data and use it in fights. Governments, \nsecret societies, religious organizations all aim to get that ability and attack it's owner. \nThere are mysteries you need to understand - what's their purpose, why you became DT master, why each data was developed and what's the secret identity of DT. But first of all you need to survive.\n\n[From [url=https://vndbreview.blogspot.com/2019/02/vn-of-month-may-2001-sapphism-no-gensou.html]vndbreview[/url]]",
  "source_sha256": "3eda461dd120bb412b2ba34959c31af0c076f838a7811cd65076190b58f5cd14",
  "translation": "你是一名DT大师。\n你能够利用收集到的数据改变物质，并将其用于战斗。政府、秘密结社和宗教组织都觊觎这种能力，纷纷向它的持有者发起袭击。\n你需要解开许多谜团：他们究竟有何目的，你为何会成为DT大师，每份数据为何被开发出来，以及DT的真实身份究竟是什么。但在此之前，你首先必须活下去。\n\n[摘自[url=https://vndbreview.blogspot.com/2019/02/vn-of-month-may-2001-sapphism-no-gensou.html]vndbreview[/url]]",
  "vndb_url": "https://vndb.org/v4081"
}

=== JiZPaper/VNDB-Description-Translations/zh-Hans/visual-novels/025/v25269.json
{
  "schema_version": 1,
  "id": "v25269",
  "type": "visual_novel",
  "name": "DearlyDialy - Dearly Diary",
  "original_name": "DearlyDialy ディアリーダイアリー",
  "language": "zh-Hans",
  "source_language": "en",
  "source": "To repay a debt, a female private tutor earns money by doing her job, and \nperhaps selling herself in this text adventure game with some simulator elements.\n\n[From [url=http://www.dlsite.com/ecchi-eng/work/=/product_id/RE245028.html]DLsite English[/url]]",
  "source_sha256": "4d70c0a911bbecf9fe81e40ab087dc2c5205cb836e60f1df9b02c8832acdf2ca",
  "translation": "为了还债，女家庭教师靠打工赚钱，\n也许在这个带有一些模拟器元素的文本冒险游戏中推销自己。\n\n[来自[url=http://www.dlsite.com/ecchi-eng/work/=/product_id/RE245028.html]DLsite英文[/url]]",
  "vndb_url": "https://vndb.org/v25269"
}

=== JiZPaper/VNDB-Description-Translations/en/characters/020/c20443.json
{
  "schema_version": 1,
  "id": "c20443",
  "type": "character",
  "name": "Komine Natsuko",
  "original_name": "小峯 夏子",
  "language": "en",
  "source_language": "en",
  "source": "“Big Sis!”—my cousin, the older sister I want to throw myself into her arms and rely on. She's cheerful, thoughtful, and deeply compassionate, valuing feelings over reason.\n\nShe runs a motorcycle delivery service for the village elders and is beloved by everyone. Her only flaw is occasionally pushing her own strong-willed, opinionated views—her “Gianism” (“What's yours is mine, and what's mine is mine”).\n\nAccording to Natsuko, she has a habit of clinging and insists it's just natural human affection, but she only does this to the protagonist, her beloved little brother figure.\n\nShe doesn't mean to seduce him, but her inherent lack of shame and guard in these matters makes her a complicated older sister with plenty of questionable behavior.\n\n[From [url=https://web.archive.org/web/20080415135100/http://www.lucha-game.com/product/oneboku/top_off.html]archived official site[/url]]",
  "source_sha256": "b5114e82dcacd0160da0cc2799846d4ef520c5f69d9a48f90cc14ce0874b6a89",
  "translation": "“Big Sis!”—my cousin, the older sister I want to throw myself into her arms and rely on. She's cheerful, thoughtful, and deeply compassionate, valuing feelings over reason.\n\nShe runs a motorcycle delivery service for the village elders and is beloved by everyone. Her only flaw is occasionally pushing her own strong-willed, opinionated views—her “Gianism” (“What's yours is mine, and what's mine is mine”).\n\nAccording to Natsuko, she has a habit of clinging and insists it's just natural human affection, but she only does this to the protagonist, her beloved little brother figure.\n\nShe doesn't mean to seduce him, but her inherent lack of shame and guard in these matters makes her a complicated older sister with plenty of questionable behavior.\n\n[From [url=https://web.archive.org/web/20080415135100/http://www.lucha-game.com/product/oneboku/top_off.html]archived official site[/url]]",
  "vndb_url": "https://vndb.org/c20443"
}

=== JiZPaper/VNDB-Description-Translations/zh-Hans/visual-novels/000/v943.json
{
  "schema_version": 1,
  "id": "v943",
  "type": "visual_novel",
  "name": "Sora no Iro, Mizu no Iro",
  "original_name": "そらのいろ、みずのいろ",
  "language": "zh-Hans",
  "source_language": "en",
  "source": "The protagonist, Saisho Hajime, finds himself stuck in remedial classes despite being on summer break. He shares this fate with Mizushima Asa, a somewhat aloof transfer student who is also on the swim team. Though Hajime tries to be friendly, Asa's responses are cold. Meanwhile, Unno Juuzou, another swim club member, notices Sorayama Natsume from the gardening club and falls for her at first sight.\n\nAs days pass, filled with remedial classes and casual swim practices, Natsume brings vegetables harvested from the garden and invites swim club members to share a meal, leading to her becoming closer to Hajime and Juuzou but remaining awkward with Asa.\n\nHoping to improve their relationship, Hajime and Juuzou organize a camping trip for the four of them. Asa and Natsume agree to go, but an incident occurs on the way back, marking the start of their hot summer story.\n\n[Translated from the [url=http://www.sp-janis.com/ciel/soranoiromizunoiro/]official site[/url]]",
  "source_sha256": "3fa43e8b1e5619fb7a55395e184ff052756fdb0423e6d4967d95015a7f740549",
  "translation": "主人公最所一因为暑假补习而无法尽情享受假期。与他同病相怜的，还有态度有些冷淡的转学生兼游泳部成员水岛朝。尽管最所一试图友好相处，朝的回应始终十分冷漠。与此同时，另一名游泳部成员海野十三注意到园艺部的空山菜摘，并对她一见钟情。\n\n补习与轻松的游泳训练一天天过去，菜摘把园艺部收获的蔬菜带来，邀请游泳部成员一同用餐。她因此与一和十三逐渐亲近，与朝相处时却依然有些尴尬。\n\n为了改善两人的关系，一和十三组织四人一起去露营。朝和菜摘同意参加，然而回程途中发生了一场意外，也拉开了他们火热夏日故事的序幕。\n\n[翻译自[url=http://www.sp-janis.com/ciel/soranoiromizunoiro/]官方网站[/url]]",
  "vndb_url": "https://vndb.org/v943"
}

=== JiZPaper/VNDB-Description-Translations/zh-Hans/visual-novels/006/v6015.json
{
  "schema_version": 1,
  "id": "v6015",
  "type": "visual_novel",
  "name": "Mad Science Love",
  "original_name": "マッドサイエンス・ラヴ",
  "language": "zh-Hans",
  "source_language": "en",
  "source": "Who would like to spend days with \"normal\" girls if there is an option? All kinds of special girls like cat ears, drill, amphibian etc fight with each other and grow up under supervision of a mad scientist.\n\n[From [url=https://vndbreview.blogspot.com/2019/03/vn-of-month-august-2001-kimi-ga-nozomu.html]vndbreview[/url]]",
  "source_sha256": "10018a4d5d5bd4c2858f9681cf17a97e43a3105cae7b07375bf6a7f7b6326eb6",
  "translation": "既然还有别的选择，谁愿意整天和“普通”少女相处？猫耳少女、钻头少女、两栖少女等形形色色的特殊少女彼此争斗，并在一名疯狂科学家的监督下成长。\n\n[摘自[url=https://vndbreview.blogspot.com/2019/03/vn-of-month-august-2001-kimi-ga-nozomu.html]vndbreview[/url]]",
  "vndb_url": "https://vndb.org/v6015"
}
